Enhanced ApplicationsInventoryExceptionMapper to work with Quarkus 1.13.0
konveyor/tackle-application-inventory pull request #22
Opened 2021-04-02 16:44 UTC by mrizzi

resolve #21

2021-04-06 10:45 UTC, m-brophy approved these changes

2021-04-06 14:47 UTC, m-brophy requested changes
Unused imports should be removed

2021-04-08 08:32 UTC, m-brophy approved these changes

2021-04-09 17:35 UTC, mrizzi commented
Considering 9ad6533 works and that Quarkus 1.13.1 has been released in the meantime, I'll keep this PR with a further commit to bump the version to be the latest available.

2021-04-13 16:13 UTC, merged