[TACKLE-93] Provide data for Adoption Suggestion Plan
konveyor/tackle-application-inventory pull request #55
Opened 2021-05-13 07:53 UTC by jonathanvila

Issue : https://github.com/konveyor/tackle-application-inventory/issues/54

Features included :
* Endpoint to serve a list of Review entities filtering by a list of ids

Steps to test :
1. clone PR
1. Start Keycloak
```
podman run -it --name keycloak --rm \
            -e KEYCLOAK_USER=admin \
            -e KEYCLOAK_PASSWORD=admin \
            -e KEYCLOAK_IMPORT=/tmp/keycloak/quarkus-realm.json \
            -e DB_VENDOR=h2 -p 8180:8080 -p 8543:8443 \
            -v ./src/main/resources/keycloak:/tmp/keycloak:Z \
            jboss/keycloak:12.0.2
```
1. Start Postgres
```
podman run -it  --name application_inventory_db \
               -e POSTGRES_USER=application_inventory \
              -e POSTGRES_PASSWORD=application_inventory \
              -e POSTGRES_DB=application_inventory_db \
             -p 5432:5432 postgres:10.6
```
1. Start Application
```
./mvnw clean quarkus:dev
```
1. Obtain Token
```
export access_token=$(\
    curl -X POST http://localhost:8180/auth/realms/quarkus/protocol/openid-connect/token \
    --user backend-service:secret \
    -H 'content-type: application/x-www-form-urlencoded' \
    -d 'username=alice&password=alice&grant_type=password' | jq --raw-output '.access_token' \
 )
```
1. Execute request
```
curl "http://localhost:8080/application-inventory/review?page=0&sort=workPriority&size=20&application.id=2&application.id=3" -H 'Accept: application/json' -H "Content-Type: application/json" \
            -H "Authorization: Bearer $access_token" \
             -v | jq

```

Expected response
```json
[
  {
    "id": 8,
    "createUser": null,
    "updateUser": null,
    "proposedAction": "Replatform",
    "effortEstimate": "2",
    "businessCriticality": 1,
    "workPriority": 1,
    "comments": "other comment",
    "application": {
      "id": 2,
      "createUser": null,
      "updateUser": null,
      "name": "Online Investments service",
      "description": "Corporate customers investments management",
      "businessService": null,
      "comments": null,
      "tags": []
    }
  },
  {
    "id": 9,
    "createUser": null,
    "updateUser": null,
    "proposedAction": "Refactor",
    "effortEstimate": "3",
    "businessCriticality": 1,
    "workPriority": 1,
    "comments": "another comment",
    "application": {
      "id": 3,
      "createUser": null,
      "updateUser": null,
      "name": "Credit Cards BS",
      "description": "Internal credit card creation and management service",
      "businessService": null,
      "comments": null,
      "tags": []
    }
  }
]

```

2021-06-08 15:36 UTC, carlosthe19916 requested changes
@jonathanvila I've added a set of minor changes I'd like to be addressed. Could you please take a look at my comments below and let me know what you think?

2021-06-08 15:36 UTC, carlosthe19916 commented on src/main/java/io/tackle/applicationinventory/services/ReportService.java
> +        planAppDto.decision = application.review.proposedAction;
This specific line is causing a "Nullpointer exception" when one of the applications being processed doesn't have a review. Could you do something so even if one of the applicationIds passed doesn't have a review the endpoint doesn't throw an exception?

2021-06-08 15:36 UTC, carlosthe19916 commented on USAGE.md
> +Filtering application ids : applicationId=<id>&applicationId=<id>&applicationId=<id>
Could we move the endpoint from `GET` to `POST` just like what we did in `tackle-pathfinder`?

2021-06-08 15:36 UTC, carlosthe19916 commented on src/main/java/io/tackle/applicationinventory/resources/ReportsResource.java
> +    public List<AdoptionPlanAppDto> getAdoptionPlanGantt(@NotNull @QueryParam("applicationId") List<Long> applicationIds) {
Could we move the endpoint from `GET` to `POST` just like what we did in `tackle-pathfinder`?

2021-06-08 15:36 UTC, carlosthe19916 commented on src/test/java/io/tackle/applicationinventory/resources/ReviewTest.java
> +                .log().all()
I suppose there is no need to touch a File this PR doesn't rely on. Could we remove it unless it is really needed?

2021-06-08 16:02 UTC, carlosthe19916 commented on src/main/java/io/tackle/applicationinventory/dto/EffortEstimate.java
> +    EXTRALARGE(8);
Could we change this to `EXTRA_LARGE`? The current UI is using `EXTRA_LARGE` already. This should be a workaround to have the same enum values in the UI and the backend.

The `effortEstimate` is a `String` value coming from the UI and there is nothing that prevents having different values  from the enum `EffortEstimate` you defined. For instance, the UI right now will set `EXTRA_LARGE` rather than `EXTRALARGE` and as a result, we will definitely have a `No enum constant` exception. In my opinion, the effort estimate should be changed from a `String` to a `Number` or use Enums and expose that Enum so the UI can consume it. This change might be out of the scope of this PR but I'd like to know what are your thought about this @jonathanvila ?

2021-06-08 16:21 UTC, jonathanvila commented on src/main/java/io/tackle/applicationinventory/services/ReportService.java
> +        planAppDto.decision = application.review.proposedAction;
:+1:

2021-06-08 18:02 UTC, jonathanvila commented on USAGE.md
> +Filtering application ids : applicationId=<id>&applicationId=<id>&applicationId=<id>
:+1:

2021-06-08 18:11 UTC, jonathanvila commented on src/main/java/io/tackle/applicationinventory/resources/ReportsResource.java
> +    public List<AdoptionPlanAppDto> getAdoptionPlanGantt(@NotNull @QueryParam("applicationId") List<Long> applicationIds) {
:+1:

2021-06-08 18:11 UTC, jonathanvila commented on src/main/java/io/tackle/applicationinventory/resources/ReportsResource.java
> +    public List<AdoptionPlanAppDto> getAdoptionPlanGantt(@NotNull @QueryParam("applicationId") List<Long> applicationIds) {
:+1:

2021-06-08 18:11 UTC, jonathanvila commented on src/main/java/io/tackle/applicationinventory/resources/ReportsResource.java
> +    public List<AdoptionPlanAppDto> getAdoptionPlanGantt(@NotNull @QueryParam("applicationId") List<Long> applicationIds) {
:+1:

2021-06-08 18:12 UTC, jonathanvila commented on src/test/java/io/tackle/applicationinventory/resources/ReviewTest.java
> +                .log().all()
:+1:

2021-06-08 19:08 UTC, jonathanvila commented on src/main/java/io/tackle/applicationinventory/dto/EffortEstimate.java
> +    EXTRALARGE(8);
As you can see by the code, these values are not used in any DTO returned by the resource. Is an internal convenient in order to not use String but type safe enums.

2021-06-08 20:11 UTC, carlosthe19916 requested changes

2021-06-08 20:11 UTC, carlosthe19916 commented on src/main/java/io/tackle/applicationinventory/services/ReportService.java
> +        planAppDto.effort = EffortEstimate.getEnum(application.review.effortEstimate).getEffort();
## Change Enum
@jonathanvila I must insist on changing enum

from:
```
enum EffortEstimate {  
    EXTRALARGE(8);
}
```

To:
```
enum EffortEstimate {  
    EXTRA_LARGE(8);
}
```

If I deploy this PR to the upshift environment it will generate exceptions `Caused by: java.lang.IllegalArgumentException: No enum constant io.tackle.applicationinventory.dto.EffortEstimate.EXTRA_LARGE`

The reason is that there is already rows with the value `EXTRA_LARGE` with an underscore and this PR is expecting `EXTRALARGE` without underscore.

## Can we avoid breaking the response if `EffortEstimate.getEnum` throws an exception?
The method `getEnum` from `EffortEstimate` is a potential source of exceptions since any `String` that doesn't match the Enum values will throw an exception making the whole Request invalid. Can we use `try, catch` when inferring the Enum value so we avoid destroying the response?

If the `application.review.effortEstimate` can not be converted into any Enum value then I would expect to skip the application just like when the application doesn't have a review.

2021-06-09 07:28 UTC, jonathanvila commented on pom.xml
> +    <maven.compiler.target>11</maven.compiler.target>
Why do we need to move to Java 1.8 ? Quarkus 1.13 works on Java 11 not on Java 8 afaik.

2021-06-09 07:41 UTC, jonathanvila commented on src/main/java/io/tackle/applicationinventory/services/ReportService.java
> +        planAppDto.effort = EffortEstimate.getEnum(application.review.effortEstimate).getEffort();
1. The enum is used to avoid open strings , because the formula needs a numeric effort associated to each string
2. The "EXTRA LARGE" value was created like this based on the script V20210420.2__insert_review.sql

I will add the underscore as you requested. 
And wait for the decision about what happens with efforts with different values, so defaulting to a certain value.

2021-06-09 08:29 UTC, carlosthe19916 commented on pom.xml
> +    <maven.compiler.target>11</maven.compiler.target>
Here is one important link we can use:
https://quarkus.io/blog/quarkus-1-3-1-final-released/

My understanding is that Java 11 is the default version; however, java 8 is still supported. Here are some quotes:
- "From now on, newly generated projects target Java 11 by default,"
- "If you use Java 8 to create a project locally, the project still targets Java 8 though."
- "We plan to drop Java 8 support in a few releases, probably around 1.6."

We will need to upgrade to Java 11 sooner or later for sure, I'd just like to do the upgrade in a separate PR.

2021-06-09 08:39 UTC, carlosthe19916 commented on pom.xml
> +    <maven.compiler.target>11</maven.compiler.target>
After the internal chat with @jonathanvila we concluded that in any case we execute the GH action tests and create the container images based on Java 11 and not based on Java 8. Here is the code for the Java version in GH actions https://github.com/konveyor/tackle-application-inventory/blob/main/.github/workflows/pull_request.yml#L38 

It makes sense to synchronize the pom.xml file with what we define in all of our GH actions.

2021-06-09 12:43 UTC, jonathanvila commented on src/main/java/io/tackle/applicationinventory/services/ReportService.java
> +        planAppDto.effort = EffortEstimate.getEnum(application.review.effortEstimate).getEffort();
Applications with a Review.Effort value not present in the Enum : 
1. will log a warning
2. will be not included in the output

2021-06-10 05:40 UTC, carlosthe19916 commented
Thanks @jonathanvila . This PR looks good to me.

2021-06-10 05:41 UTC, merged